name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs JUnit tests
      - name: Run JUnit Tests
        run: |
             find -name "*.java" > sources.txt
             javac -d "bin" -cp "lib/junit-4.13.2.jar" @sources.txt 
             java -jar "lib/junit-platform-console-standalone-1.8.2.jar" -cp "bin" --scan-classpath